-- SES Platform shared database schema for Supabase PostgreSQL.
-- Run this in Supabase SQL Editor before deploying the backend.

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  technical_id text,
  name text not null unique,
  material_category text not null default 'fiber',
  fiber_family text,
  thickness_mm double precision not null,
  areal_weight_g_m2 double precision not null,
  fiber_type text not null check (fiber_type in ('unidirectional', 'bidirectional')),
  resin_fraction double precision not null default 0,
  e1_pa double precision,
  e2_pa double precision,
  g12_pa double precision,
  poisson_input double precision,
  density_kg_m3 double precision,
  strength_x_mpa double precision,
  strength_x_compression_mpa double precision,
  strength_y_mpa double precision,
  strength_y_compression_mpa double precision,
  strength_s_mpa double precision,
  aliases text,
  notes text,
  created_at text not null
);

create table if not exists public.core_materials (
  id bigint generated by default as identity primary key,
  key text not null unique,
  technical_id text,
  name text not null unique,
  type text not null default 'core',
  material_category text not null default 'core',
  fiber_family text,
  thickness_mm double precision not null,
  density_kg_m3 double precision not null default 0,
  e1_pa double precision,
  e2_pa double precision,
  g12_pa double precision,
  poisson_input double precision,
  strength_x_mpa double precision,
  strength_x_compression_mpa double precision,
  strength_y_mpa double precision,
  strength_y_compression_mpa double precision,
  strength_s_mpa double precision,
  aliases text,
  notes text,
  mechanical_notes text,
  geometry_notes text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.specimens (
  id text primary key,
  test_type text not null,
  laminate_json jsonb not null default '[]'::jsonb,
  theoretical_json jsonb not null default '{}'::jsonb,
  real_weight_g double precision,
  real_thickness_mm double precision,
  core_material text,
  core_thickness_mm double precision,
  skin_thickness_mm double precision,
  top_skin_thickness_mm double precision,
  bottom_skin_thickness_mm double precision,
  computed_json jsonb not null default '{}'::jsonb,
  raw_points_json jsonb not null default '[]'::jsonb,
  reduced_points_json jsonb not null default '[]'::jsonb,
  selected_points_json jsonb not null default '[]'::jsonb,
  comments text,
  source_filename text,
  created_at text not null,
  updated_at text not null
);

create index if not exists idx_specimens_test_type on public.specimens(test_type);
create index if not exists idx_specimens_updated_at on public.specimens(updated_at);

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null unique,
  panels_json jsonb not null default '[]'::jsonb,
  dashboard_json jsonb not null default '{}'::jsonb,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.monocoque_weight_calculations (
  id bigint generated by default as identity primary key,
  name text not null,
  car_id bigint references public.cars(id) on delete set null,
  car_snapshot_json jsonb not null default '{}'::jsonb,
  assignments_json jsonb not null default '{}'::jsonb,
  front_hoop_volume_mm3 double precision,
  front_hoop_density_kg_mm3 double precision,
  hardpoints_weight_g double precision,
  computed_json jsonb not null default '{}'::jsonb,
  created_at text not null,
  updated_at text not null
);

create index if not exists idx_monocoque_updated_at on public.monocoque_weight_calculations(updated_at);

create table if not exists public.car_probe_metrics (
  car_id bigint not null references public.cars(id) on delete cascade,
  specimen_id text not null references public.specimens(id) on delete cascade,
  metrics_json jsonb not null default '{}'::jsonb,
  status text not null default 'ok',
  error text,
  updated_at text not null,
  primary key (car_id, specimen_id)
);

create index if not exists idx_car_probe_metrics_car on public.car_probe_metrics(car_id);
create index if not exists idx_car_probe_metrics_specimen on public.car_probe_metrics(specimen_id);

alter table public.materials enable row level security;
alter table public.core_materials enable row level security;
alter table public.specimens enable row level security;
alter table public.cars enable row level security;
alter table public.monocoque_weight_calculations enable row level security;
alter table public.car_probe_metrics enable row level security;

drop policy if exists "public read materials" on public.materials;
drop policy if exists "authenticated write materials" on public.materials;
create policy "public read materials" on public.materials for select using (true);
create policy "authenticated write materials" on public.materials for all to authenticated using (true) with check (true);

drop policy if exists "public read core_materials" on public.core_materials;
drop policy if exists "authenticated write core_materials" on public.core_materials;
create policy "public read core_materials" on public.core_materials for select using (true);
create policy "authenticated write core_materials" on public.core_materials for all to authenticated using (true) with check (true);

drop policy if exists "public read specimens" on public.specimens;
drop policy if exists "authenticated write specimens" on public.specimens;
create policy "public read specimens" on public.specimens for select using (true);
create policy "authenticated write specimens" on public.specimens for all to authenticated using (true) with check (true);

drop policy if exists "public read cars" on public.cars;
drop policy if exists "authenticated write cars" on public.cars;
create policy "public read cars" on public.cars for select using (true);
create policy "authenticated write cars" on public.cars for all to authenticated using (true) with check (true);

drop policy if exists "public read monocoque_weight_calculations" on public.monocoque_weight_calculations;
drop policy if exists "authenticated write monocoque_weight_calculations" on public.monocoque_weight_calculations;
create policy "public read monocoque_weight_calculations" on public.monocoque_weight_calculations for select using (true);
create policy "authenticated write monocoque_weight_calculations" on public.monocoque_weight_calculations for all to authenticated using (true) with check (true);

drop policy if exists "public read car_probe_metrics" on public.car_probe_metrics;
drop policy if exists "authenticated write car_probe_metrics" on public.car_probe_metrics;
create policy "public read car_probe_metrics" on public.car_probe_metrics for select using (true);
create policy "authenticated write car_probe_metrics" on public.car_probe_metrics for all to authenticated using (true) with check (true);
